"""empty message

Revision ID: 0a7386d661bf
Revises: d9ace4f26b95
Create Date: 2021-02-09 22:28:16.449691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7386d661bf'
down_revision = 'd9ace4f26b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_id_key', 'test', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('test_id_key', 'test', ['id'])
    # ### end Alembic commands ###
