"""empty message

Revision ID: be1366449618
Revises: 09d41f3b0af6
Create Date: 2020-11-23 18:06:20.068260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be1366449618'
down_revision = '09d41f3b0af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('museums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('floor_count', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('museum_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('map', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('museum_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('tour_count', sa.BigInteger(), nullable=True),
    sa.Column('interaction_count', sa.BigInteger(), nullable=True),
    sa.Column('question_count', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exhibits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('questions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('answers', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('museum_id', sa.Integer(), nullable=True),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.Column('tour_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibit_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('era', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('dimension', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('coordinates', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('notes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('questions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('answers', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['exhibit_id'], ['exhibits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stations_pkey')
    )
    op.drop_table('pieces')
    op.drop_table('tours')
    op.drop_table('exhibits')
    op.drop_table('robots')
    op.drop_table('floors')
    op.drop_table('museums')
    # ### end Alembic commands ###
