"""empty message

Revision ID: d79238924684
Revises: 0a7386d661bf
Create Date: 2021-02-09 22:39:10.813481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79238924684'
down_revision = '0a7386d661bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'test', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='unique')
    # ### end Alembic commands ###
